# Generated by Django 3.1 on 2020-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_users_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='foto',
            field=models.ImageField(upload_to='./userImage'),
        ),
    ]
